import pandas as pd
from typing import Dict, List, Any

class PnLAttributionEngine:
    """
    Decomposes PnL to understand exactly where profit comes from.
    Allows institutional shops to explain portfolio returns by strategy,
    style (Trend, Mean Reversion, Volatility, Gap, etc.), and regime.
    """
    def __init__(self):
        self.trade_history = []
        
    def add_trade_pnl(self, strategy_id: str, style: str, pnl: float, capital_used: float, regime: str = "normal"):
        """Log a completed trade's PnL."""
        self.trade_history.append({
            "strategy_id": strategy_id,
            "style": style,
            "pnl": pnl,
            "capital_used": capital_used,
            "regime": regime
        })
        
    def get_attribution_by_style(self) -> Dict[str, float]:
        """Returns the percentage of total PnL generated by each style."""
        if not self.trade_history:
            return {}
            
        df = pd.DataFrame(self.trade_history)
        total_pnl = df['pnl'].sum()
        if total_pnl == 0:
            return {}
            
        style_pnl = df.groupby('style')['pnl'].sum()
        return (style_pnl / total_pnl * 100).to_dict()

    def get_attribution_by_strategy(self) -> Dict[str, float]:
        """Returns the absolute PnL generated by each individual strategy."""
        if not self.trade_history:
            return {}
            
        df = pd.DataFrame(self.trade_history)
        return df.groupby('strategy_id')['pnl'].sum().to_dict()

    def get_attribution_by_regime(self) -> Dict[str, float]:
        """Returns the percentage of total PnL generated in each market regime."""
        if not self.trade_history:
            return {}
            
        df = pd.DataFrame(self.trade_history)
        total_pnl = df['pnl'].sum()
        if total_pnl == 0:
            return {}
            
        regime_pnl = df.groupby('regime')['pnl'].sum()
        return (regime_pnl / total_pnl * 100).to_dict()
        
    def generate_report(self) -> Dict[str, Any]:
        """Generate a complete attribution report."""
        return {
            "total_trades": len(self.trade_history),
            "by_style_pct": self.get_attribution_by_style(),
            "by_strategy_abs": self.get_attribution_by_strategy(),
            "by_regime_pct": self.get_attribution_by_regime()
        }
