"""
Signal Monitor
Daily monitoring of strategy performance with automated alerts and allocation reduction.
"""

from enum import Enum
from dataclasses import dataclass, field
from datetime import datetime, date, timedelta
from typing import Dict, List, Optional
import numpy as np


class AlertLevel(Enum):
    """Alert severity levels"""
    P1 = "P1"  # Urgent - automatic action
    P2 = "P2"  # Warning - manual review


@dataclass
class SignalMetrics:
    """Metrics tracked per strategy"""
    strategy_id: str
    date: date
    
    # Current metrics
    current_rolling_sharpe_20d: float
    expected_sharpe: float
    current_rolling_win_rate: float
    expected_win_rate: float
    current_information_coefficient: float
    expected_ic: float
    current_max_drawdown_20d: float
    expected_max_drawdown: float
    
    # Additional context
    daily_return: float = 0.0
    position_count: int = 0
    
    def sharpe_drop_pct(self) -> float:
        """Calculate Sharpe drop percentage relative to expected"""
        if self.expected_sharpe == 0:
            return 0.0
        return ((self.current_rolling_sharpe_20d - self.expected_sharpe) / self.expected_sharpe) * 100
    
    def ic_drop_pct(self) -> float:
        """Calculate IC drop percentage relative to expected"""
        if self.expected_ic == 0:
            return 0.0
        return ((self.current_information_coefficient - self.expected_ic) / self.expected_ic) * 100
    
    def drawdown_exceedance(self) -> float:
        """Calculate how much current drawdown exceeds expected"""
        if self.expected_max_drawdown == 0:
            return 0.0
        return self.current_max_drawdown_20d / self.expected_max_drawdown
    
    def win_rate_drop_pct(self) -> float:
        """Calculate win rate drop percentage relative to expected"""
        if self.expected_win_rate == 0:
            return 0.0
        return ((self.current_rolling_win_rate - self.expected_win_rate) / self.expected_win_rate) * 100


@dataclass
class Alert:
    """Alert generated by signal monitor"""
    strategy_id: str
    date: date
    level: AlertLevel
    metric_name: str
    current_value: float
    expected_value: float
    threshold: float
    message: str
    action_taken: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict:
        return {
            "strategy_id": self.strategy_id,
            "date": self.date.isoformat(),
            "level": self.level.value,
            "metric_name": self.metric_name,
            "current_value": self.current_value,
            "expected_value": self.expected_value,
            "threshold": self.threshold,
            "message": self.message,
            "action_taken": self.action_taken,
            "created_at": self.created_at.isoformat(),
        }


class SignalMonitor:
    """
    Monitors strategy performance daily and generates alerts.
    Automatically reduces allocation on P1 alerts.
    """
    
    def __init__(self):
        self.metrics_history: Dict[str, List[SignalMetrics]] = {}
        self.alerts: List[Alert] = []
        self.allocation_multipliers: Dict[str, float] = {}
        
        # Alert thresholds
        self.p1_sharpe_drop_threshold = 30.0  # 30% drop
        self.p1_ic_drop_threshold = 40.0  # 40% drop
        self.p2_drawdown_exceedance = 1.5  # 1.5x expected
        self.p2_win_rate_drop_threshold = 20.0  # 20% drop
    
    def record_metrics(self, metrics: SignalMetrics) -> None:
        """Record daily metrics for a strategy"""
        strategy_id = metrics.strategy_id
        if strategy_id not in self.metrics_history:
            self.metrics_history[strategy_id] = []
            self.allocation_multipliers[strategy_id] = 1.0
        
        self.metrics_history[strategy_id].append(metrics)
        
        # Keep only last 90 days of history
        if len(self.metrics_history[strategy_id]) > 90:
            self.metrics_history[strategy_id] = self.metrics_history[strategy_id][-90:]
    
    def evaluate_metrics(self, metrics: SignalMetrics) -> List[Alert]:
        """Evaluate metrics and generate alerts"""
        alerts = []
        
        # P1 Alert: Sharpe drop > 30%
        sharpe_drop = metrics.sharpe_drop_pct()
        if sharpe_drop < -self.p1_sharpe_drop_threshold:
            alert = Alert(
                strategy_id=metrics.strategy_id,
                date=metrics.date,
                level=AlertLevel.P1,
                metric_name="rolling_sharpe_20d",
                current_value=metrics.current_rolling_sharpe_20d,
                expected_value=metrics.expected_sharpe,
                threshold=self.p1_sharpe_drop_threshold,
                message=f"Sharpe dropped {abs(sharpe_drop):.1f}% relative to expected"
            )
            alerts.append(alert)
        
        # P1 Alert: IC drop > 40%
        ic_drop = metrics.ic_drop_pct()
        if ic_drop < -self.p1_ic_drop_threshold:
            alert = Alert(
                strategy_id=metrics.strategy_id,
                date=metrics.date,
                level=AlertLevel.P1,
                metric_name="information_coefficient",
                current_value=metrics.current_information_coefficient,
                expected_value=metrics.expected_ic,
                threshold=self.p1_ic_drop_threshold,
                message=f"IC dropped {abs(ic_drop):.1f}% relative to expected"
            )
            alerts.append(alert)
        
        # P2 Alert: Drawdown exceeds expected 1.5x
        dd_exceedance = metrics.drawdown_exceedance()
        if dd_exceedance > self.p2_drawdown_exceedance:
            alert = Alert(
                strategy_id=metrics.strategy_id,
                date=metrics.date,
                level=AlertLevel.P2,
                metric_name="max_drawdown_20d",
                current_value=metrics.current_max_drawdown_20d,
                expected_value=metrics.expected_max_drawdown,
                threshold=self.p2_drawdown_exceedance,
                message=f"Drawdown is {dd_exceedance:.1f}x expected"
            )
            alerts.append(alert)
        
        # P2 Alert: Win rate drop > 20%
        win_rate_drop = metrics.win_rate_drop_pct()
        if win_rate_drop < -self.p2_win_rate_drop_threshold:
            alert = Alert(
                strategy_id=metrics.strategy_id,
                date=metrics.date,
                level=AlertLevel.P2,
                metric_name="rolling_win_rate",
                current_value=metrics.current_rolling_win_rate,
                expected_value=metrics.expected_win_rate,
                threshold=self.p2_win_rate_drop_threshold,
                message=f"Win rate dropped {abs(win_rate_drop):.1f}% relative to expected"
            )
            alerts.append(alert)
        
        return alerts
    
    def process_metrics(self, metrics: SignalMetrics) -> Dict:
        """
        Process metrics: record, evaluate, and take automatic actions.
        Returns summary of actions taken.
        """
        # Record metrics
        self.record_metrics(metrics)
        
        # Evaluate and generate alerts
        alerts = self.evaluate_metrics(metrics)
        
        result = {
            "strategy_id": metrics.strategy_id,
            "date": metrics.date.isoformat(),
            "alerts_generated": len(alerts),
            "alerts": [],
            "allocation_multiplier": self.allocation_multipliers[metrics.strategy_id],
            "actions_taken": []
        }
        
        for alert in alerts:
            self.alerts.append(alert)
            result["alerts"].append(alert.to_dict())
            
            # Take automatic action for P1 alerts
            if alert.level == AlertLevel.P1:
                old_multiplier = self.allocation_multipliers[metrics.strategy_id]
                self.allocation_multipliers[metrics.strategy_id] *= 0.5
                alert.action_taken = f"Reduced allocation from {old_multiplier:.2f} to {self.allocation_multipliers[metrics.strategy_id]:.2f}"
                result["actions_taken"].append(alert.action_taken)
                result["allocation_multiplier"] = self.allocation_multipliers[metrics.strategy_id]
        
        return result
    
    def get_allocation_multiplier(self, strategy_id: str) -> float:
        """Get current allocation multiplier for a strategy"""
        return self.allocation_multipliers.get(strategy_id, 1.0)
    
    def get_recent_alerts(self, strategy_id: Optional[str] = None, days: int = 7) -> List[Dict]:
        """Get recent alerts, optionally filtered by strategy"""
        cutoff_date = datetime.now() - timedelta(days=days)
        
        alerts = [
            alert for alert in self.alerts
            if alert.created_at >= cutoff_date
            and (strategy_id is None or alert.strategy_id == strategy_id)
        ]
        
        return [alert.to_dict() for alert in alerts]
    
    def get_metrics_history(self, strategy_id: str, days: int = 30) -> List[Dict]:
        """Get metrics history for a strategy"""
        if strategy_id not in self.metrics_history:
            return []
        
        cutoff_date = date.today() - timedelta(days=days)
        recent_metrics = [
            m for m in self.metrics_history[strategy_id]
            if m.date >= cutoff_date
        ]
        
        return [
            {
                "date": m.date.isoformat(),
                "current_rolling_sharpe_20d": m.current_rolling_sharpe_20d,
                "expected_sharpe": m.expected_sharpe,
                "current_rolling_win_rate": m.current_rolling_win_rate,
                "expected_win_rate": m.expected_win_rate,
                "current_information_coefficient": m.current_information_coefficient,
                "expected_ic": m.expected_ic,
                "current_max_drawdown_20d": m.current_max_drawdown_20d,
                "expected_max_drawdown": m.expected_max_drawdown,
                "daily_return": m.daily_return,
            }
            for m in recent_metrics
        ]
    
    def reset_allocation_multiplier(self, strategy_id: str) -> None:
        """Reset allocation multiplier to 1.0 (manual override)"""
        self.allocation_multipliers[strategy_id] = 1.0
    
    def get_all_strategies(self) -> List[str]:
        """Get list of all monitored strategies"""
        return list(self.metrics_history.keys())
